### ISSUE TITLE
Publish codacy-plugins-test as a docker

### ISSUE THREAD

**Issue by mrfyda** [codacy/codacy-plugins-test#10]
Contributors should have to setup a Scala environment just to test their engine.
We could solve this by providing codacy-plugins-test as a docker.

**Comment by machadoit** [comment]
Just a bit afraid I may be a bit confusing for someone not used to dockers, but it really makes sense. I like it, and we can do it.

**Comment by rtfpessoa** [comment]
I think it makes sense, I already created a task on Jira.
