### ISSUE TITLE
Bad behavior in `multiple` test when running with extra options

### ISSUE THREAD

**Issue by ljmf00** [codacy/codacy-plugins-test#99]
When I pass a property in the root node of the `patterns.xml` file, the value got converted when using decimals. Imagine you pass a property `php_version` with `7.0` value. This `7.0` value is converted to `7` and the test fails. [1]

## Reference
1. https://github.com/codacy/codacy-plugins-test/blob/master/src/main/scala/codacy/plugins/test/multiple/CheckstyleFormatParser.scala#L36

**Comment by lolgab** [comment]
I think it is not a bug in codacy-plugins-test. The tool wanted a parameter of type string.
When you use
```
<property name="php_version" value="7.0" />
```
The value is being parsed as a Json number value. Then is passed to the tool as a number ( 7 in this case) which is a correct json number value.
The tool, instead, is expecting a string with the version.
You should enforce that passing a Json string to the property:
```
<property name="php_version" value="&quot;7.0&quot;" />
```

**Comment by ljmf00** [comment]
Thanks, it worked that way. Sorry for false positive a bug :/
